mobile version
egorka193/landing-html-css pull request #3
Opened 2024-11-28 12:20 UTC by egorka193

2024-11-28 18:57 UTC, Platon79 commented
- у кнопки hero__purchase высота почти 30 пикселей, а в дизайне 36. В десктопе
- у кнопки hero__learn неправильные размер, жирность шрифта, цвет бордера, border-radius. Также у этой кнопки

2024-11-28 18:58 UTC, Platon79 commented
блок header до сих пор имеет отступ сверху с помощью margin, из-за чего обрезается картинка фона. Я уже просил это исправить

2024-11-28 19:01 UTC, Platon79 commented
не понимаю, зачем блоку `.fast__card-left` нужен  `padding: 40px 0px;`
объясни мне завтра, но это наверняка неверно и стоит исправить

2024-11-28 19:03 UTC, Platon79 commented
Блок `.fast__cards`
Вертикальный отступы 300 пикселей должны быть не у этого блока, а у `background__wrapper-rectangle`, потому что именно он отталкивается от других блоков

2024-11-28 19:05 UTC, Platon79 commented
блок `.fast__text-first`
у тебя нижний отступ 160, а в дизайне 80

2024-11-28 19:06 UTC, Platon79 commented
между `.fast__minicard h3` и `.fast__minicard p` нету отступов. А в дизайне 6 пикселей

2024-11-28 19:10 UTC, Platon79 commented
во многих местах установлен неправильный line-height

2024-11-28 19:12 UTC, Platon79 commented
у ссылок footer__link-second неправильные цвета. При этом видно по коду, что у родителя указан верный цвет, а у детей он уже неверный

2024-11-28 19:13 UTC, Platon79 commented
у hr в футере неправильный цвет

2024-11-28 19:53 UTC, Platon79 commented
нужно сделать что-то с футером. Сейчас выглядит не оч
![image](https://github.com/user-attachments/assets/0618e494-d082-4f33-b02e-f74e9406c989)

2024-11-28 20:04 UTC, Platon79 requested changes

2024-11-28 20:04 UTC, Platon79 commented on scss/_header.scss
> +    .header__wrapper{
видно, что тут ты отправляешь элементы хедера в свободное плавание, давая им возможность обтекать друг друга. Но лучше сделать так, чтобы после 650px они четко вставали друг под друга. Причем в идеале сначала логотип, потом ссылки, потом кнопка

2024-11-28 20:04 UTC, Platon79 commented on scss/_fast.scss
> +        width: 100%;
картинки становятся сильно большими на мобильных устройствах. Давай лучше дадим им 200пикселей высоты, а ширина сама подстроится

2024-11-28 20:04 UTC, Platon79 commented on scss/_fast.scss
> +        width: 100%;
ну и по центру их разместим конечно

2024-11-29 10:00 UTC, egorka193 commented on scss/_header.scss
> +    .header__wrapper{
resolve

2024-11-29 11:11 UTC, Platon79 commented on scss/_fast.scss
>      button {
зачем тут заново писать селектор `.fast__card-left`? он уже написан на строке 6. Там и нужно добавлять стили для button

2024-11-29 11:11 UTC, Platon79 commented on scss/_fast.scss
>      button {
тоже самое для `.fast__minicard img`

2024-11-29 11:13 UTC, Platon79 commented on scss/_footer.scss
>  .logo {
этот  стиль у тебя уже есть для хедера. Не нужно его писать второй раз

2024-11-29 11:14 UTC, Platon79 commented on scss/_footer.scss
>  hr{
лучше сделать селектор `.footer hr {}`. Иначе если у тебя появится второй тэг hr, к нему применятся те же стили

2024-11-29 11:16 UTC, Platon79 commented on scss/_footer.scss
> +    border: 0.3px solid;
1) не стоит делать дробное значения для пикселей. Если ты утсановишь 1пиксель, то скорее всего не почувствуешь разницы
2) для hr лучше дать высоту и backroung-color.

2024-11-29 11:17 UTC, Platon79 commented on scss/_header.scss
>  body{
этот  стиль не относится к header. Его стоит перенести в general.scss

2024-11-29 11:17 UTC, Platon79 commented on scss/_header.scss
>  body{
тоже самое для `.container`

2024-11-29 11:18 UTC, Platon79 commented on scss/_header.scss
> +    .logp__top{
logp__top - такого класса у тебя нету

2024-11-29 11:19 UTC, Platon79 commented on scss/_price.scss
> +
в начале файла есть селектор `.price img{`
img стоит вкладывать внутрь селектора .price

2024-11-29 11:20 UTC, Platon79 commented on scss/_price.scss
> +@media (max-width: 600px){
нужно определиться и использовать одну ширину для мобильных устройств. Тут у тебя это 600, в другом файле 650. Чтобы не ошибаться, положи это значение в переменную и используй ее

2024-12-01 14:56 UTC, egorka193 commented on scss/_fast.scss
>      button {
resolve

2024-12-01 14:59 UTC, egorka193 commented on scss/_footer.scss
>  .logo {
resolve

2024-12-01 15:00 UTC, egorka193 commented on scss/_footer.scss
>  hr{
resolve

2024-12-01 15:50 UTC, egorka193 commented on scss/_footer.scss
> +    border: 0.3px solid;
resolve 1/2

2024-12-01 15:53 UTC, egorka193 commented on scss/_header.scss
> +    .logp__top{
resolve

2024-12-01 15:53 UTC, egorka193 commented on scss/_price.scss
> +
resolve

2024-12-01 16:11 UTC, egorka193 commented on scss/_price.scss
> +@media (max-width: 600px){
resolve

2024-12-01 16:12 UTC, egorka193 commented on scss/_header.scss
>  body{
resolve 1/2

2024-12-02 08:53 UTC, Platon79 commented on scss/_price.scss
> +@media (max-width: 600px){
нужно переименовать пременную

2024-12-02 09:08 UTC, Platon79 commented on scss/_footer.scss
>  hr{
в начале файла уже есть селектор .footer, так что можно hr туда же вложить

2024-12-02 09:33 UTC, merged